#!/usr/bin/env Rscript

# Generate inst/AUTHORS and inst/LICENCE.note for bundled SIMDe headers.
# Run from the RsimdDispatch package root:
#   Rscript tools/update-authors.R

root <- normalizePath(".", mustWork = TRUE)
vendor_dir <- file.path(root, "inst", "vendor", "simde")
version_file <- file.path(vendor_dir, "VERSION")
contributors_file <- file.path(vendor_dir, "all-contributors.json")
copying_file <- file.path(vendor_dir, "COPYING")

if (!file.exists(version_file)) {
  stop("Cannot find ", version_file, call. = FALSE)
}
if (!file.exists(copying_file)) {
  stop("Cannot find ", copying_file, call. = FALSE)
}

read_field <- function(field) {
  lines <- readLines(version_file, warn = FALSE)
  value <- sub(paste0("^", field, ":\\s*"), "", grep(paste0("^", field, ":"), lines, value = TRUE)[1])
  if (is.na(value)) "unknown" else value
}

simde_version <- read_field("Version")
simde_commit <- read_field("Commit")
simde_url <- read_field("Repository")
simde_date <- read_field("Date")

contributors <- character()
if (file.exists(contributors_file)) {
  txt <- paste(readLines(contributors_file, warn = FALSE), collapse = "\n")
  matches <- gregexpr('"name"[[:space:]]*:[[:space:]]*"([^"\\\\]|\\\\.)*"', txt, perl = TRUE)[[1]]
  if (!identical(matches, -1L)) {
    raw <- regmatches(txt, list(matches))[[1]]
    contributors <- sub('^"name"[[:space:]]*:[[:space:]]*"', "", raw, perl = TRUE)
    contributors <- sub('"$', "", contributors)
    contributors <- gsub('\\\\"', '"', contributors)
    contributors <- unique(contributors[nzchar(contributors)])
  }
}

if (!length(contributors)) {
  contributors <- "See https://github.com/simd-everywhere/simde/graphs/contributors"
}

dir.create(file.path(root, "inst"), showWarnings = FALSE)

writeLines(
  c(
    "Generated by tools/update-authors.R; do not edit by hand.",
    "",
    "RsimdDispatch bundles the header-only SIMDe library in inst/include/simde.",
    "",
    sprintf("Upstream repository: %s", simde_url),
    sprintf("Vendored version: %s", simde_version),
    sprintf("Vendored commit: %s", simde_commit),
    sprintf("Vendored commit date: %s", simde_date),
    "",
    "SIMDe copyright holder from upstream COPYING:",
    "  Evan Nemerson <evan@nemerson.com>",
    "",
    "SIMDe contributors recorded by upstream all-contributors metadata:",
    paste0("  ", contributors)
  ),
  file.path(root, "inst", "AUTHORS")
)

copying <- readLines(copying_file, warn = FALSE)
writeLines(
  c(
    "Generated by tools/update-authors.R; do not edit by hand.",
    "",
    "RsimdDispatch bundles SIMDe as a vendored, header-only third-party component.",
    "",
    "Bundled component: SIMDe",
    sprintf("Upstream repository: %s", simde_url),
    "Vendored include tree: inst/include/simde",
    sprintf("Vendored version: %s", simde_version),
    sprintf("Vendored commit: %s", simde_commit),
    sprintf("Vendored commit date: %s", simde_date),
    "",
    "SIMDe licensing:",
    "The upstream COPYING file is reproduced below.",
    "",
    "----- BEGIN SIMDe COPYING -----",
    copying,
    "----- END SIMDe COPYING -----",
    "",
    "RsimdDispatch package licensing:",
    "The RsimdDispatch package code is licensed under GPL (>= 2), as declared in DESCRIPTION.",
    "This notice documents bundled third-party components and does not modify the package license."
  ),
  file.path(root, "inst", "LICENCE.note")
)

message("Wrote inst/AUTHORS and inst/LICENCE.note")
